### ISSUE TITLE
Move downloaded packages into node_modules/.download/

### ISSUE THREAD

**Issue by STRML** [alexanderGugel/ied#96] opened 2016-03-23 14:25 UTC
One of my favorite things about npm@2 was how easy it was to look at your node_modules folder and get a sense of your dependencies. And when debugging something inside them, it was very easy to get to the dependency you want and insert debugging information.

For example, very readable directory structure from npm@2 (this is ied's folder itself):

![screen shot 2016-03-23 at 8 52 22 am](https://cloud.githubusercontent.com/assets/1197375/13987299/e5964a14-f0d4-11e5-8a2c-6ae5ff2bfa2d.jpg)

And from npm@3, something much more verbose, but still usable:

![screen shot 2016-03-23 at 8 55 42 am](https://cloud.githubusercontent.com/assets/1197375/13987346/1e197032-f0d5-11e5-8dcd-37beb70cb187.jpg)

Yet with ied:

![screen shot 2016-03-23 at 8 56 48 am](https://cloud.githubusercontent.com/assets/1197375/13987358/3829d75a-f0d5-11e5-9ddf-f82daeb44bf9.jpg)

This is very hard to use, at least until you get past 'f':

![screen shot 2016-03-23 at 8 57 24 am](https://cloud.githubusercontent.com/assets/1197375/13987382/4d0107c0-f0d5-11e5-9cc0-d5fc6556a57a.jpg)

We could fix this usability issue by moving all the actual packages into a subfolder like `.download`, leading to this much simplified structure:

```bash
cd node_modules
mkdir .download
find . -regex '\./[a-f0-9]*' -type d -maxdepth 1 | xargs -J % mv % .download
# this only fixes the top-level deps, would have to recursively fixup the symlinks to do this right
for i in $(find . -type l -depth 1); do
  ln -sf ./.download/$(readlink $i) $i
done
```

![screen shot 2016-03-23 at 9 24 17 am](https://cloud.githubusercontent.com/assets/1197375/13988265/2fd656f6-f0d9-11e5-986a-c3778b8b6483.jpg)

Thoughts? Would be happy to contribute a PR.

**Comment by just-boris** [comment] 2016-03-23 14:32
As for me, it looks reasonable. I also considered to do something like this

**Comment by alexanderGugel** [comment] 2016-03-24 02:51
Yes, readability and debuggability is definitely a fair point here... on the other hand names are not guaranteed to be unique (currently they are, because there is only a single registry, but this could/should change in the future).

If we can come up with a design that allow us to keep the CAS structure will having nice names as above, that would be awesome.

Moving away from the CAS completely is an option as well at this point. It's not as useful as I thought in the beginning.

**Comment by STRML** [comment] 2016-03-24 02:53
If the names weren't unique, it would completely kill npm disk structure as
well. I think we gain a lot of warning from that. Let's address it as it
comes.

Don't drop CAS. It's what makes this project unique.

**Comment by RangerMauve** [comment] 2016-03-28 19:47
In terms of unique names, I think that's sort of happening with [scopes](https://docs.npmjs.com/getting-started/scoped-packages), but the name is getting prefixed by the scope so it ends up being unique either way.

**Comment by alexanderGugel** [comment] 2016-04-12 20:11
@RangerMauve Not across registries. We're not going to drop the CAS. Latest changes are on `rebirth` branch. I know this is kind of weird, but creating additional symlinks for no significant benefit is not a good idea IMO. I see why this is appealing and kind of nice, but I don't think this should be the default behaviour.

**Comment by alexanderGugel** [comment] 2016-05-27 01:42
Closing, this is by design. You made a fair point, but this would ruin the current architecture.

**Closed by alexanderGugel** 2016-05-27 01:42 UTC
