### ISSUE TITLE
TypeError: Cannot read property 'dist' of null

### ISSUE THREAD

**Issue by trusktr** [alexanderGugel/ied#47] opened 2015-12-09 08:12 UTC
I got this when running `ied install` inside of [bootstrap@181f76f](https://github.com/twbs/bootstrap/commit/181f76f115a35c03c5e7629af670fea144ee25dd).

```
> ied install
/usr/lib/node_modules/ied/lib/expose.js:47
  debug('expose %s in %s', pkg.dist.shasum, dir)
                              ^

TypeError: Cannot read property 'dist' of null
    at expose (/usr/lib/node_modules/ied/lib/expose.js:47:31)
    at /usr/lib/node_modules/ied/node_modules/async/lib/async.js:356:13
    at async.forEachOf.async.eachOf (/usr/lib/node_modules/ied/node_modules/async/lib/ac.js:233:13)
    at _asyncMap (/usr/lib/node_modules/ied/node_modules/async/lib/async.js:355:9)
    at Object.map (/usr/lib/node_modules/ied/node_modules/async/lib/async.js:337:20)
    at expose (/usr/lib/node_modules/ied/lib/expose.js:42:11)
    at fn (/usr/lib/node_modules/ied/node_modules/async/lib/async.js:741:34)
    at /usr/lib/node_modules/ied/node_modules/async/lib/async.js:1208:16
    at /usr/lib/node_modules/ied/node_modules/async/lib/async.js:166:37
    at /usr/lib/node_modules/ied/node_modules/async/lib/async.js:701:43
```

**Comment by alexanderGugel** [comment] 2015-12-10 08:56
Thanks for reporting. Can't reproduce. What version of ied are you running?

**Comment by trusktr** [comment] 2015-12-11 10:00
I'm running `ied version 0.3.5` from NPM.

**Comment by narma** [comment] 2016-01-15 22:59
I've got same issue, `ied version 0.3.6`

**Comment by narma** [comment] 2016-01-15 23:11
Some debug info, hope it will be useful
```js
break in /usr/lib/node_modules/ied/bin/cmd.js:3
  1 
  2 
> 3 var fs = require('fs')
  4 var path = require('path')
  5 var minimist = require('minimist')
debug> c
break in /usr/lib/node_modules/ied/lib/expose.js:49
 47   // console.dir(pkg);
 48   if (!pkg) {
>49 	 debugger;
 50   }
 51   debug('expose %s in %s', pkg.dist.shasum, dir)
debug> repl
Press Ctrl + C to leave debug repl
> dir
'/home/narma/w/ashes/node_modules'
debug> bt
#0 expose.js:49:3
#1 async.js:356:13
#2 async.forEachOf.async.eachOf async.js:233:13
#3 async.js:355:9
#4 async.js:337:20
#5 expose.js:42:11
#6 async.js:746:34
#7 async.js:1213:16
#8 async.js:166:37
#9 async.js:706:43
```

**Comment by just-boris** [comment] 2016-01-15 23:39
Bootstrap has a non-npm dependency:
```
 "grunt-sed": "twbs/grunt-sed#v0.2.0",
```

It is not supported for now. So the erorr is expected and might be better and descriptive with my PR #50

**Comment by alexanderGugel** [comment] 2016-05-27 02:26
Known issue, won't be fixed in foreseeable future. Just use "real" npm packages.

**Closed by alexanderGugel** 2016-05-27 02:26 UTC
Labels: wontfix
